# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o savingsAccountImplementation.o bankAccountImplementation.o checkingAccountImplementation.o checkingAccountImplementation.o serviceChargeCheckingImplementation.o noServiceChargeCheckingImplementation.o highInterestCheckingImplementation.o highInterestSavingsImplementation.o certificateOfDepositIimplementation.o
LINKOBJ  = main.o savingsAccountImplementation.o bankAccountImplementation.o checkingAccountImplementation.o checkingAccountImplementation.o serviceChargeCheckingImplementation.o noServiceChargeCheckingImplementation.o highInterestCheckingImplementation.o highInterestSavingsImplementation.o certificateOfDepositIimplementation.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Project 5.exe"
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

savingsAccountImplementation.o: savingsAccountImplementation.cpp
	$(CPP) -c savingsAccountImplementation.cpp -o savingsAccountImplementation.o $(CXXFLAGS)

bankAccountImplementation.o: bankAccountImplementation.cpp
	$(CPP) -c bankAccountImplementation.cpp -o bankAccountImplementation.o $(CXXFLAGS)

checkingAccountImplementation.o: checkingAccountImplementation.cpp
	$(CPP) -c checkingAccountImplementation.cpp -o checkingAccountImplementation.o $(CXXFLAGS)

checkingAccountImplementation.o: checkingAccountImplementation.cpp
	$(CPP) -c checkingAccountImplementation.cpp -o checkingAccountImplementation.o $(CXXFLAGS)

serviceChargeCheckingImplementation.o: serviceChargeCheckingImplementation.cpp
	$(CPP) -c serviceChargeCheckingImplementation.cpp -o serviceChargeCheckingImplementation.o $(CXXFLAGS)

noServiceChargeCheckingImplementation.o: noServiceChargeCheckingImplementation.cpp
	$(CPP) -c noServiceChargeCheckingImplementation.cpp -o noServiceChargeCheckingImplementation.o $(CXXFLAGS)

highInterestCheckingImplementation.o: highInterestCheckingImplementation.cpp
	$(CPP) -c highInterestCheckingImplementation.cpp -o highInterestCheckingImplementation.o $(CXXFLAGS)

highInterestSavingsImplementation.o: highInterestSavingsImplementation.cpp
	$(CPP) -c highInterestSavingsImplementation.cpp -o highInterestSavingsImplementation.o $(CXXFLAGS)

certificateOfDepositIimplementation.o: certificateOfDepositIimplementation.cpp
	$(CPP) -c certificateOfDepositIimplementation.cpp -o certificateOfDepositIimplementation.o $(CXXFLAGS)
